version: "3"

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/hosts/:/etc/nginx/conf.d/
      - ./docker/nginx/log/:/var/log/nginx/
      - ./:/var/www/site/
    depends_on:
      - php_fpm

  php_fpm:
    build: ./docker/php_fpm
    restart: always
    volumes:
      - ./docker/php_fpm/log/:/var/log/
      - ./:/var/www/site/
    depends_on:
      - database

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    restart: always
    environment:
      # POSTGRES_DB: ${POSTGRES_DB:-sa}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_USER: ${POSTGRES_USER:-sa}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
    # - ./docker/db/data:/var/lib/postgresql/data:rw
    ###< doctrine/doctrine-bundle ###
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGAMIN_PASSWORD:-admin@local.ru}
      PGADMIN_DEFAULT_PASSWORD: ${PGAMIN_PASSWORD:-1234}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      # - ./docker/pgadmin:/var/lib/pgadmin:rw
      - pgadmin_data:/var/lib/pgadmin:rw
    ports:
      - 5050:80
    restart: always
    depends_on:
      - database

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
    ###< doctrine/doctrine-bundle ###
    driver: local
  pgadmin_data:
    driver: local
